# =============================================================================
# EcoGuard AI - Module 3: Climate Awareness Chatbot
# =============================================================================
# Responses are generated by IBM Granite (ibm/granite-4-h-small) via the
# shared utils/watsonx_client.py.
#
# The static keyword-matching fallback has been replaced by the IBM model.
# If IBM credentials are missing or the service is unavailable, the module
# returns a clear, honest error message — never a fake AI response.
# =============================================================================

from utils.watsonx_client import chat as watsonx_chat

# ---------------------------------------------------------------------------
# System prompt — defines EcoGuard AI's persona and boundaries
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = (
    "You are EcoGuard AI, an educational climate and sustainability assistant. "
    "Provide accurate, practical, easy-to-understand information about climate change, "
    "climate risks, sustainability, waste reduction, biodiversity, carbon footprint, "
    "and the UN Sustainable Development Goals (SDGs). "
    "Do not invent statistics or claim live information unless it comes from a "
    "connected, verified data source. "
    "Clearly distinguish general educational information from live observational data. "
    "Encourage users to follow official local emergency and environmental guidance "
    "for high-risk situations such as floods, heatwaves, or wildfires. "
    "Keep answers concise (3–5 paragraphs maximum) and suitable for a general audience."
)

# ---------------------------------------------------------------------------
# Topics list (used by the UI's 'Topics I can answer' section)
# ---------------------------------------------------------------------------

_SUPPORTED_TOPICS = [
    "climate change",
    "carbon footprint",
    "greenhouse gases",
    "global warming",
    "sea level rise",
    "heatwaves",
    "floods & extreme rainfall",
    "drought",
    "wildfires",
    "deforestation",
    "renewable energy",
    "sustainability",
    "biodiversity",
    "Paris Agreement",
    "SDG 13 – Climate Action",
    "waste reduction",
    "electric vehicles",
    "ocean acidification",
    "permafrost",
    "climate resilience",
]


# ---------------------------------------------------------------------------
# Public interface
# ---------------------------------------------------------------------------

def get_chatbot_response(user_question: str, history: list[dict] | None = None) -> str:
    """
    Send *user_question* to IBM Granite and return the generated text.

    Args:
        user_question: The user's question string.
        history:       Optional list of previous {"role", "content"} dicts
                       for multi-turn context (role must be "user" or "assistant").

    Returns:
        The model's response text, or a safe error message string.
        Never returns a fake AI answer.
    """
    if not user_question or not user_question.strip():
        return "Please enter a question to get started."

    # Build the message list: system → previous turns → current user message
    messages: list[dict] = [{"role": "system", "content": _SYSTEM_PROMPT}]

    if history:
        for turn in history:
            role    = turn.get("role", "")
            content = turn.get("content", "")
            if role in ("user", "assistant") and content:
                messages.append({"role": role, "content": content})

    messages.append({"role": "user", "content": user_question.strip()})

    text, error = watsonx_chat(messages)
    if error:
        return error
    return text if text else "⚠️ EcoGuard AI received an empty response. Please try again."


def list_supported_topics() -> list[str]:
    """Return the list of topics the assistant can discuss."""
    return _SUPPORTED_TOPICS
